/**
 * kami-lens vendor port (AGPL-3.0 — see LICENSE).
 * upstream: Asphodel-OS/kamigotchi @ ffda396330af1bc33238b6c37188772152b45439
 * path:     packages/client/types/ethers-contracts/index.ts
 * changes:  partial port — upstream's autogenerated barrel exports every
 *           typechain contract type (hundreds of system/component types used
 *           by the transaction layer). kami-lens ports only what the sync
 *           layer consumes: the World contract type. Lines kept are verbatim.
 */

export type { World } from './World';
