/**
 * kami-lens vendor port (AGPL-3.0 — see LICENSE).
 * upstream: Asphodel-OS/kamigotchi @ ef898fc9350a6085fb080419b12af96c2254e8f3
 * path:     packages/client/types/ethers-contracts/World.ts
 * changes:  none
 */

/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface WorldInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "_emitter"
      | "cancelOwnershipHandover"
      | "completeOwnershipHandover"
      | "components"
      | "getUniqueEntityId"
      | "init"
      | "owner"
      | "ownershipHandoverExpiresAt"
      | "register"
      | "registerComponent"
      | "registerComponentValueRemoved"
      | "registerComponentValueSet"
      | "registerSystem"
      | "renounceOwnership"
      | "requestOwnershipHandover"
      | "systems"
      | "transferOwnership"
      | "updateEmitter"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ComponentRegistered"
      | "ComponentValueRemoved"
      | "ComponentValueSet"
      | "EmitterUpdated"
      | "OwnershipHandoverCanceled"
      | "OwnershipHandoverRequested"
      | "OwnershipTransferred"
      | "SystemRegistered"
  ): EventFragment;

  encodeFunctionData(functionFragment: "_emitter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cancelOwnershipHandover",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "completeOwnershipHandover",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "components",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUniqueEntityId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "init", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownershipHandoverExpiresAt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "register", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerComponent",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerComponentValueRemoved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerComponentValueSet",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerSystem",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestOwnershipHandover",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "systems", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateEmitter",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "_emitter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelOwnershipHandover",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeOwnershipHandover",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "components", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUniqueEntityId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ownershipHandoverExpiresAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerComponent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerComponentValueRemoved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerComponentValueSet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerSystem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestOwnershipHandover",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "systems", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateEmitter",
    data: BytesLike
  ): Result;
}

export namespace ComponentRegisteredEvent {
  export type InputTuple = [componentId: BigNumberish, component: AddressLike];
  export type OutputTuple = [componentId: bigint, component: string];
  export interface OutputObject {
    componentId: bigint;
    component: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComponentValueRemovedEvent {
  export type InputTuple = [
    componentId: BigNumberish,
    component: AddressLike,
    entity: BigNumberish
  ];
  export type OutputTuple = [
    componentId: bigint,
    component: string,
    entity: bigint
  ];
  export interface OutputObject {
    componentId: bigint;
    component: string;
    entity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComponentValueSetEvent {
  export type InputTuple = [
    componentId: BigNumberish,
    component: AddressLike,
    entity: BigNumberish,
    data: BytesLike
  ];
  export type OutputTuple = [
    componentId: bigint,
    component: string,
    entity: bigint,
    data: string
  ];
  export interface OutputObject {
    componentId: bigint;
    component: string;
    entity: bigint;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmitterUpdatedEvent {
  export type InputTuple = [emitter: AddressLike];
  export type OutputTuple = [emitter: string];
  export interface OutputObject {
    emitter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipHandoverCanceledEvent {
  export type InputTuple = [pendingOwner: AddressLike];
  export type OutputTuple = [pendingOwner: string];
  export interface OutputObject {
    pendingOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipHandoverRequestedEvent {
  export type InputTuple = [pendingOwner: AddressLike];
  export type OutputTuple = [pendingOwner: string];
  export interface OutputObject {
    pendingOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [oldOwner: string, newOwner: string];
  export interface OutputObject {
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SystemRegisteredEvent {
  export type InputTuple = [systemId: BigNumberish, system: AddressLike];
  export type OutputTuple = [systemId: bigint, system: string];
  export interface OutputObject {
    systemId: bigint;
    system: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface World extends BaseContract {
  connect(runner?: ContractRunner | null): World;
  waitForDeployment(): Promise<this>;

  interface: WorldInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  _emitter: TypedContractMethod<[], [string], "view">;

  cancelOwnershipHandover: TypedContractMethod<[], [void], "payable">;

  completeOwnershipHandover: TypedContractMethod<
    [pendingOwner: AddressLike],
    [void],
    "payable"
  >;

  components: TypedContractMethod<[], [string], "view">;

  getUniqueEntityId: TypedContractMethod<[], [bigint], "nonpayable">;

  init: TypedContractMethod<[], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  ownershipHandoverExpiresAt: TypedContractMethod<
    [pendingOwner: AddressLike],
    [bigint],
    "view"
  >;

  register: TypedContractMethod<[], [string], "view">;

  registerComponent: TypedContractMethod<
    [addr: AddressLike, id: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerComponentValueRemoved: TypedContractMethod<
    [entity: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerComponentValueSet: TypedContractMethod<
    [entity: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;

  registerSystem: TypedContractMethod<
    [addr: AddressLike, id: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "payable">;

  requestOwnershipHandover: TypedContractMethod<[], [void], "payable">;

  systems: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "payable"
  >;

  updateEmitter: TypedContractMethod<
    [emitter: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "_emitter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelOwnershipHandover"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "completeOwnershipHandover"
  ): TypedContractMethod<[pendingOwner: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "components"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getUniqueEntityId"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "init"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownershipHandoverExpiresAt"
  ): TypedContractMethod<[pendingOwner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerComponent"
  ): TypedContractMethod<
    [addr: AddressLike, id: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerComponentValueRemoved"
  ): TypedContractMethod<[entity: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerComponentValueSet"
  ): TypedContractMethod<
    [entity: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerSystem"
  ): TypedContractMethod<
    [addr: AddressLike, id: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "requestOwnershipHandover"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "systems"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "updateEmitter"
  ): TypedContractMethod<[emitter: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ComponentRegistered"
  ): TypedContractEvent<
    ComponentRegisteredEvent.InputTuple,
    ComponentRegisteredEvent.OutputTuple,
    ComponentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ComponentValueRemoved"
  ): TypedContractEvent<
    ComponentValueRemovedEvent.InputTuple,
    ComponentValueRemovedEvent.OutputTuple,
    ComponentValueRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ComponentValueSet"
  ): TypedContractEvent<
    ComponentValueSetEvent.InputTuple,
    ComponentValueSetEvent.OutputTuple,
    ComponentValueSetEvent.OutputObject
  >;
  getEvent(
    key: "EmitterUpdated"
  ): TypedContractEvent<
    EmitterUpdatedEvent.InputTuple,
    EmitterUpdatedEvent.OutputTuple,
    EmitterUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipHandoverCanceled"
  ): TypedContractEvent<
    OwnershipHandoverCanceledEvent.InputTuple,
    OwnershipHandoverCanceledEvent.OutputTuple,
    OwnershipHandoverCanceledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipHandoverRequested"
  ): TypedContractEvent<
    OwnershipHandoverRequestedEvent.InputTuple,
    OwnershipHandoverRequestedEvent.OutputTuple,
    OwnershipHandoverRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SystemRegistered"
  ): TypedContractEvent<
    SystemRegisteredEvent.InputTuple,
    SystemRegisteredEvent.OutputTuple,
    SystemRegisteredEvent.OutputObject
  >;

  filters: {
    "ComponentRegistered(uint256,address)": TypedContractEvent<
      ComponentRegisteredEvent.InputTuple,
      ComponentRegisteredEvent.OutputTuple,
      ComponentRegisteredEvent.OutputObject
    >;
    ComponentRegistered: TypedContractEvent<
      ComponentRegisteredEvent.InputTuple,
      ComponentRegisteredEvent.OutputTuple,
      ComponentRegisteredEvent.OutputObject
    >;

    "ComponentValueRemoved(uint256,address,uint256)": TypedContractEvent<
      ComponentValueRemovedEvent.InputTuple,
      ComponentValueRemovedEvent.OutputTuple,
      ComponentValueRemovedEvent.OutputObject
    >;
    ComponentValueRemoved: TypedContractEvent<
      ComponentValueRemovedEvent.InputTuple,
      ComponentValueRemovedEvent.OutputTuple,
      ComponentValueRemovedEvent.OutputObject
    >;

    "ComponentValueSet(uint256,address,uint256,bytes)": TypedContractEvent<
      ComponentValueSetEvent.InputTuple,
      ComponentValueSetEvent.OutputTuple,
      ComponentValueSetEvent.OutputObject
    >;
    ComponentValueSet: TypedContractEvent<
      ComponentValueSetEvent.InputTuple,
      ComponentValueSetEvent.OutputTuple,
      ComponentValueSetEvent.OutputObject
    >;

    "EmitterUpdated(address)": TypedContractEvent<
      EmitterUpdatedEvent.InputTuple,
      EmitterUpdatedEvent.OutputTuple,
      EmitterUpdatedEvent.OutputObject
    >;
    EmitterUpdated: TypedContractEvent<
      EmitterUpdatedEvent.InputTuple,
      EmitterUpdatedEvent.OutputTuple,
      EmitterUpdatedEvent.OutputObject
    >;

    "OwnershipHandoverCanceled(address)": TypedContractEvent<
      OwnershipHandoverCanceledEvent.InputTuple,
      OwnershipHandoverCanceledEvent.OutputTuple,
      OwnershipHandoverCanceledEvent.OutputObject
    >;
    OwnershipHandoverCanceled: TypedContractEvent<
      OwnershipHandoverCanceledEvent.InputTuple,
      OwnershipHandoverCanceledEvent.OutputTuple,
      OwnershipHandoverCanceledEvent.OutputObject
    >;

    "OwnershipHandoverRequested(address)": TypedContractEvent<
      OwnershipHandoverRequestedEvent.InputTuple,
      OwnershipHandoverRequestedEvent.OutputTuple,
      OwnershipHandoverRequestedEvent.OutputObject
    >;
    OwnershipHandoverRequested: TypedContractEvent<
      OwnershipHandoverRequestedEvent.InputTuple,
      OwnershipHandoverRequestedEvent.OutputTuple,
      OwnershipHandoverRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SystemRegistered(uint256,address)": TypedContractEvent<
      SystemRegisteredEvent.InputTuple,
      SystemRegisteredEvent.OutputTuple,
      SystemRegisteredEvent.OutputObject
    >;
    SystemRegistered: TypedContractEvent<
      SystemRegisteredEvent.InputTuple,
      SystemRegisteredEvent.OutputTuple,
      SystemRegisteredEvent.OutputObject
    >;
  };
}
